version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet pack
test_script:
- cmd: dotnet test .\GoogleCloudPrintApi.Tests\GoogleCloudPrintApi.Tests.csproj
artifacts:
- path: GoogleCloudPrintApi/bin/Debug/GoogleCloudPrintApi.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: acSSgAlUNA/OCqX0TVICWNqcNcYgBJi01ynOZwXGhTNGVNtRQiv4FIJFsoYnuSgB